name = "SpatialLightModulator"
uuid = "8496614f-bc0d-4828-b8a6-7044d7be1234"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
