name = "SpatialLightModulator"
uuid = "8496614f-bc0d-4828-b8a6-7044d7be1234"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
