name = "SpatialLightModulator"
uuid = "8496614f-bc0d-4828-b8a6-7044d7be1234"
authors = ["Marcos Gil <marcosgildeoliveira@gmail.com>"]
version = "0.2.1"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
GLFW = "3"
ModernGL = "1"
PrecompileTools = "1"
julia = "^1.10"
